#!/usr/bin/env python3
"""Generate public feature and settings references from canonical sources."""

from __future__ import annotations

import argparse
import configparser
import difflib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SETTINGS_SOURCE = REPO_ROOT / "settings.lua"
AI_CONSTANTS_SOURCE = REPO_ROOT / "src/core/aiConstants.lua"
LOCALE_SOURCE = REPO_ROOT / "locale/en/sceatorio.cfg"
FEATURE_SOURCE = REPO_ROOT / "portal/feature-contract.json"
SETTINGS_OUTPUT = REPO_ROOT / "docs/settings.md"
FEATURE_OUTPUT = REPO_ROOT / "docs/features.md"


@dataclass(frozen=True)
class Setting:
    kind: str
    name: str
    scope: str
    default: str
    minimum: str | None
    maximum: str | None
    allowed: tuple[str, ...]


def balanced_blocks(text: str) -> list[str]:
    blocks: list[str] = []
    position = 0
    marker = re.compile(r'type\s*=\s*"(?:bool|int|double|string)-setting"')
    while match := marker.search(text, position):
        start = text.rfind("{", 0, match.start())
        if start < 0:
            raise ValueError("setting has no opening brace")
        depth = 0
        quoted = False
        escaped = False
        for index in range(start, len(text)):
            character = text[index]
            if quoted:
                if escaped:
                    escaped = False
                elif character == "\\":
                    escaped = True
                elif character == '"':
                    quoted = False
                continue
            if character == '"':
                quoted = True
            elif character == "{":
                depth += 1
            elif character == "}":
                depth -= 1
                if depth == 0:
                    blocks.append(text[start : index + 1])
                    position = index + 1
                    break
        else:
            raise ValueError("unterminated setting block")
    return blocks


def field(block: str, name: str) -> str | None:
    match = re.search(
        rf"\b{re.escape(name)}\s*=\s*(\"(?:[^\"\\]|\\.)*\"|true|false|-?[0-9]+(?:\.[0-9]+)?|[A-Za-z_][A-Za-z0-9_.]*)",
        block,
    )
    return match.group(1) if match else None


def default_capabilities_csv() -> str:
    source = AI_CONSTANTS_SOURCE.read_text(encoding="utf-8")
    match = re.search(r"Constants\.CAPABILITIES\s*=\s*\{(.*?)\}", source, re.S)
    if not match:
        raise ValueError("aiConstants.lua has no Constants.CAPABILITIES table")
    capabilities = re.findall(r'"([^"\\]*(?:\\.[^"\\]*)*)"', match.group(1))
    if not capabilities:
        raise ValueError("aiConstants.lua has an empty Constants.CAPABILITIES table")
    return ",".join(capabilities)


def scalar(value: str | None) -> str | None:
    if value is None:
        return None
    if value.startswith('"'):
        return json.loads(value)
    if value == "AiConstants.DEFAULT_CAPABILITIES_CSV":
        return default_capabilities_csv()
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.]*", value) and value not in {"true", "false"}:
        raise ValueError(f"unsupported setting constant: {value}")
    return value


def parse_settings() -> list[Setting]:
    settings: list[Setting] = []
    for block in balanced_blocks(SETTINGS_SOURCE.read_text(encoding="utf-8")):
        kind = scalar(field(block, "type"))
        name = scalar(field(block, "name"))
        scope = scalar(field(block, "setting_type"))
        default = scalar(field(block, "default_value"))
        if not all((kind, name, scope, default is not None)):
            raise ValueError(f"incomplete setting block: {block[:80]!r}")
        allowed_match = re.search(r"\ballowed_values\s*=\s*\{([^}]*)\}", block, re.S)
        allowed = tuple(re.findall(r'"([^"\\]*(?:\\.[^"\\]*)*)"', allowed_match.group(1))) if allowed_match else ()
        settings.append(
            Setting(
                kind=str(kind),
                name=str(name),
                scope=str(scope),
                default=str(default),
                minimum=scalar(field(block, "minimum_value")),
                maximum=scalar(field(block, "maximum_value")),
                allowed=allowed,
            )
        )
    if not settings:
        raise ValueError("settings.lua contains no settings")
    return settings


def locale() -> configparser.ConfigParser:
    parser = configparser.ConfigParser(interpolation=None, delimiters=("="), strict=True)
    parser.optionxform = str
    parser.read(LOCALE_SOURCE, encoding="utf-8")
    return parser


def render_settings() -> str:
    translations = locale()
    names = translations["mod-setting-name"]
    descriptions = translations["mod-setting-description"]
    lines = [
        "<!-- Generated by scripts/sync_docs.py from settings.lua and locale/en/sceatorio.cfg. -->",
        "# Runtime settings",
        "",
        "These are Factorio runtime settings. Most are administrator-controlled runtime-global map settings; entries marked runtime-per-user are personal options. Dedicated deployments may reconcile runtime-global settings through private RCON.",
        "",
    ]
    for setting in parse_settings():
        display = names.get(setting.name)
        description = descriptions.get(setting.name)
        if not display or not description:
            raise ValueError(f"missing English locale for {setting.name}")
        kind = setting.kind.removesuffix("-setting")
        lines.extend(
            [
                f"## {display}",
                "",
                f"`{setting.name}` · `{setting.scope}` · `{kind}`",
                "",
                description,
                "",
                f"Default: `{setting.default}`.",
            ]
        )
        if setting.allowed:
            labels = []
            localized = translations["string-mod-setting"]
            for value in setting.allowed:
                key = f"{setting.name}-{value}"
                labels.append(f"`{value}` ({localized.get(key, value)})")
            lines.extend(["", "Allowed values: " + ", ".join(labels) + "."])
        if setting.minimum is not None or setting.maximum is not None:
            lines.extend(
                [
                    "",
                    f"Range: `{setting.minimum or 'unbounded'}` to `{setting.maximum or 'unbounded'}`.",
                ]
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_features() -> str:
    contract = json.loads(FEATURE_SOURCE.read_text(encoding="utf-8"))
    lines = [
        "<!-- Generated by scripts/sync_docs.py from portal/feature-contract.json. -->",
        "# Feature contract",
        "",
        f"Target: {contract['target']}.",
        "",
        "This is the concise public contract. The implementation and tests referenced in the source contract are the evidence; future plans are not listed as shipped features.",
        "",
        "## Implemented",
        "",
    ]
    for feature in contract["implemented"]:
        lines.append(f"- **{feature['label']}:** {feature['statement']}")
    lines.extend(["", "## Explicit limitations", ""])
    for limitation in contract["limitations"]:
        lines.append(f"- **{limitation['label']}:** {limitation['statement']}")
    lines.append("")
    return "\n".join(lines)


def compare(path: Path, expected: str) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        return True
    print(
        "".join(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(path.relative_to(REPO_ROOT)),
                tofile=f"generated:{path.relative_to(REPO_ROOT)}",
            )
        ),
        file=sys.stderr,
    )
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated references")
    mode.add_argument("--check", action="store_true", help="fail when generated references drift")
    arguments = parser.parse_args()
    outputs = {
        SETTINGS_OUTPUT: render_settings(),
        FEATURE_OUTPUT: render_features(),
    }
    if arguments.write:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        return 0
    return 0 if all(compare(path, content) for path, content in outputs.items()) else 1


if __name__ == "__main__":
    sys.exit(main())
